### ISSUE TITLE
Issue with Pro and Private Repos

### ISSUE THREAD

**Issue by harlanhaskins** [NapCat-App/Support#14]
I purchased NapCat Pro and I still can't see my private repositories. Is there something I'm missing to be able to view them in the source viewer?

Thanks,
Harlan

**Comment by zetachang** [comment]
Hi Harlan,

Currently there are two ways to access your private repository,

1) Search for it by repo name
2) Star the repo on the desktop browser, and it will appear in the "Public Activity" section in "My Profile".

Sorry for causing this inconvenience, private repos will be easier to access in the next update. Thanks for your patience.

Happy reading code!

David

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:

**Comment by nigon135** [comment]
on issue

**Comment by nigon135** [comment]
on issue
