### ISSUE TITLE
Every time I search by user name NapCat dies

### ISSUE THREAD

**Issue by xen** [NapCat-App/Support#2]
Steps to reproduce: 
- open NapCat 
- select Search tab
- switch to user tab
- enter 'xen' 
- client dies every time

**Comment by zetachang** [comment]
Hi, thanks for reporting this. :+1: 

We will fix on that in the next release (v1.4.0). Sorry for the inconvenience :sweat_smile:

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
