### ISSUE TITLE
Crash while downloading torvalds Linux from git hub

### ISSUE THREAD

**Issue by wilesduan** [NapCat-App/Support#20]
Search linux 
Chose torvalds's branch
Crash after 5 or more minutes

Please solve this problem

**Comment by zetachang** [comment]
Hi,

Sorry for the late reply. Currently, the app crash while downloading big repository. We are surveying the issue and will try to fix this in the next update. Thanks for reporting :smile:

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
