### ISSUE TITLE
Unable to log out

### ISSUE THREAD

**Issue by ebridges** [NapCat-App/Support#26]
I'm not able to log out of my github account.

**Comment by zetachang** [comment]
Hi,

Could you provide more information on this issue? (e.g. error messages and how to reproduce)

**Comment by ebridges** [comment]
I don't see a function for doing this. Am I missing something?

**Comment by zetachang** [comment]
There is a button "Account" on the upper left which will prompt "Logout" when you are already logged in.

**Comment by ebridges** [comment]
Hmm. Nothing happens when I click that button. (I'm logged in) using iOS 7.0.4 on an iPad mini retina.

**Comment by zetachang** [comment]
The logout button currently won't show in portrait mode. You can turn the device in horizontal position thus the logout button will show correctly.

![screen shot 2014-01-04 at 10 54 05](https://f.cloud.github.com/assets/839973/1844760/4696aece-7550-11e3-87bf-1bb0623b84a7.png)

**Comment by ebridges** [comment]
Works for me, thanks!
