### ISSUE TITLE
Unable to view private repos

### ISSUE THREAD

**Issue by ebridges** [NapCat-App/Support#27]
I have some private repos connected to my account, but after purchasing (in app) they are not visible.

**Comment by zetachang** [comment]
Hi, 

This is a bug indeed.  And currently, the workaround is to search by the repo name.

Hope this we will help. :smile: 

Regards

**Comment by ebridges** [comment]
Well, I paid for the app to get this (advertised) feature.  Why are you marketing this feature on the app when it's not present?

**Comment by zetachang** [comment]
Hi,

Sorry for the misleading marketing words. We will consider to remove them from our app description until it get fixed.

Sincerely.

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
