### ISSUE TITLE
Can't find private repo

### ISSUE THREAD

**Issue by danielcompton** [NapCat-App/Support#28]
I'm trying to search for a private repo I have access to under a different org. I have paid for the full version but I still can't see it. Can you help?

**Comment by zetachang** [comment]
Hi,

You can currently search for its name to access it, sorry for this inconvenience. We are rolling out a new version fixing this issue. We really appreciate your patience :smile: 

Cheers!

**Comment by danielcompton** [comment]
I’m still not seeing it when I search for orgname/repo name. Is there something else I have to do?

Daniel.

**Comment by zetachang** [comment]
Hi Daniel,

Would you mind using the beta by click this link (http://tflig.ht/1c1H8mT) and follow its instruction? I can send you a latest build which fixing the issue.

Again, apologize for the inconvenience.

Best Regards.

**Comment by danielcompton** [comment]
Sure thing

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
