### ISSUE TITLE
Minor grammar correction...

### ISSUE THREAD

**Issue by zer0her0** [NapCat-App/Support#3]
On the front page of the app it says: 
A github client for open source explorer

It should say:
A github client for the open source explorer

Or:
A github client for open source explorers

Hope this helps,
--zer0her0

**Comment by zetachang** [comment]
Thanks for pointing this out, I will change it in the next version :+1:

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
