### ISSUE TITLE
Unable to save repo for reading

### ISSUE THREAD

**Issue by rgoulter** [NapCat-App/Support#38]
Consistently given "error, try again later".

**Comment by zetachang** [comment]
Hi, 

Thanks for reporting this. I am looking into the issue and will get back to you soon.

Sorry for the inconvenience. :sweat:

**Comment by zetachang** [comment]
Hi,

I've discovered that the issue is caused by the changing api format from github. It has beed fixed and will be delivered in the next update. Really appreciate your waiting :smiley_cat:

**Comment by zetachang** [comment]
Finally, it has arrived App Store. Please download or upgrade to the latest version (1.4.0). It should be fixed.

Download link: https://itunes.apple.com/us/app/napcat-github-client-for-open/id606238223?mt=8

**Comment by rgoulter** [comment]
Yup, got the latest version and it works. :-) Thanks.
