### ISSUE TITLE
Can't see my private repo

### ISSUE THREAD

**Issue by themaxx75** [NapCat-App/Support#4]
Tried logging out, deleting the app... Would appreciate some help resolving the issue. Thanks

**Comment by zetachang** [comment]
Hi, currently the only way to see private repo is by searching. We will show them in starred section and profile section in next version. 

Hope this will help :-)

**Comment by themaxx75** [comment]
Thanks for the workaround ;)
Looking forward  to see the next version.

Keep up the good work!

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
