### ISSUE TITLE
Can not download to read

### ISSUE THREAD

**Issue by Gohan** [NapCat-App/Support#40]

**Comment by zetachang** [comment]
This is a bug caused by Github api change, we are preparing the next update. Sorry for the inconvenience. :sweat:

**Comment by zetachang** [comment]
Finally, it has arrived App Store. Please download or upgrade to the latest version (1.4.0). It should be fixed.

Download link: https://itunes.apple.com/us/app/napcat-github-client-for-open/id606238223?mt=8
