### ISSUE TITLE
Cannot download code

### ISSUE THREAD

**Issue by pspencil** [NapCat-App/Support#41]
Whenever i tried to download, private or public repo, it always says cannot download currently

**Comment by zetachang** [comment]
Hi, 

We have delivered a new update with bug fix to Apple, it won't take too long for the update to be available. 

Sorry for the inconvenience again! :smile:

**Comment by zetachang** [comment]
Finally, it has arrived App Store. Please download or upgrade to the latest version (1.4.0). It should be fixed.

Download link: https://itunes.apple.com/us/app/napcat-github-client-for-open/id606238223?mt=8
