### ISSUE TITLE
Private repo

### ISSUE THREAD

**Issue by gpolguere** [NapCat-App/Support#6]
Hey!
Your app looks great but I can't see any of my private repo...

**Comment by zetachang** [comment]
Hi, glad you like it!

In the current version , the only way to see private repo is by searching them... this is not intended and will be fixed in next release.  Until then, you can see your private repos in profile and also stars (if you starred them).  

Sorry for the inconvenience :sweat:

**Comment by gpolguere** [comment]
Hello !
Well, it wasn't working with profile or search neither... :/ I'll wait for
the next updates :)
Best

**Comment by zetachang** [comment]
Hi,

It's weird that it doesn't work with search. Would you mind giving me the search query and the repo name you are finding? I think there might be something wrong while generating the query request.

**Comment by gpolguere** [comment]
Hello David,

If I give you the name of the repo, is there any confidential issue ? I ask
you this because this is a professional project.

Best

---

Polguère Gil

**Comment by zetachang** [comment]
Hi,

There will be no confidential issue here. Sorry for not mention this. We
take your privacy seriously and all the credentials are stored at client
side only :-)

Gil Polguère 於 2013年9月16日星期一寫道：

> Hello David,
> 
> If I give you the name of the repo, is there any confidential issue ? I
> ask
> you this because this is a professional project.
> 
> Best
> 
> ---
> 
> Polguère Gil
> 
> On Mon, Sep 16, 2013 at 4:38 AM, David Chang <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>wrote:
> 
> > Hi,
> > 
> > It's weird that it doesn't work with search. Would you mind giving me
> > the
> > search query and the repo name you are finding? I think there might be
> > something wrong while generating the query request.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/NapCat-App/Support/issues/6#issuecomment-24486434>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NapCat-App/Support/issues/6#issuecomment-24502004
> .

## 

David Chang

**Comment by gpolguere** [comment]
Hello!
OK if you say so!
The repository is soleilnoir/ctc

Best

**Comment by zetachang** [comment]
Hey, 

Thanks for providing this, I believe the season why you can't search this repo is that the search term `ctc` has too many results and NapCat displays only a part of them currently. 

Don't worry, this will all be fixed in next update. Thank you for being patient about this. 

Cheers.

**Comment by zetachang** [comment]
This issue has been fixed in the latest version (1.3.1). Thanks for the patience and have fun reading code!

Cheers! :beers:
