### ISSUE TITLE
Verifying error on my iPad2

### ISSUE THREAD

**Issue by newliver** [NapCat-App/Support#9]
Why?

**Comment by zetachang** [comment]
Hi, could you provide detailed steps to produce the error? Thus we can help you solving the problem :smile:

**Comment by newliver** [comment]
Hi，原来是台湾的朋友，那我还是用简体中文和您描述一下我的使用过程吧。
步骤如下：
1、iPhone 4s（iOS 7.0.2）未越狱，下载后安装，应用内购买，unlock成功，可以使用其他功能。
2、iPad2（iOS 6.1.4）已越狱，下载后安装，点击unlock full version 》upgrade now  》购买  》提示输入AppleID和Password 》提示我已经购买了此软件（您已经购买了此项目。轻敲“好”可免费再次下载。），点击 “好” ，提示 “verifying error”。

还有个问题就是点击“My Profile”会闪退。
thanks.

Best regards,
-newliver

在 2013-9-27，下午11:27，David Chang notifications@github.com 写道：

**Comment by zetachang** [comment]
Hi, 你好

感謝你提供那麼詳細的說明，我想最主要的原因還是因為你的 iPad 2 越獄了，NapCat 並不會去檢查裝置是否越獄，但是內購買的最後一個步驟是會跟蘋果的伺服器做認證，而可能前一步驟購買結果被越獄軟體篡改了導致無法完成認證。這方面可以要麻煩你瞭解一下是否有辦法關掉這個功能。

感謝！
